version: '3'
services:
   web:
     build: .
     ports: 
       - "5000:5000"
     depends_on:
       - 'ipfs'
   ipfs:
     image: 'ipfs/go-ipfs'
     ports: 
       - "4001:4001"
       - "5001:5001"
       - "8080:8080"
